### ISSUE TITLE
Trouble using expressions in `where`

### ISSUE THREAD

**Issue by cgarvis** [lotus/model#165]
I have the following in my repository based on #46 
```ruby
class OrderRepository
  def since(date)
    query do
      where{ created_at > date }
    end
  end
end
```
But I'm receive the following error:

```bash
     Failure/Error: recent_orders = OrderRepository.since(yesterday)                                                                                                                                       │
     ArgumentError:                                                                                                                                                                                        │
       wrong number of arguments (0 for 1)                                                                                                                                                                 │
     # ./repositories/order_repository.rb:15:in `block in since'                                                                                                                                           │
     # ./repositories/order_repository.rb:14:in `since'                                                                                                                                                    │
     # ./spec/repositories/order_repository_spec.rb:23:in `block (3 levels) in <top (required)>'
```

**Comment by cgarvis** [comment]
This works with the sql adapter.  Not on the memory.

**Comment by jodosha** [comment]
@cgarvis Hello and thanks for this issue.
We want to achieve as much as possible feature parity between adapters, where it makes sense.
We haven't implemented it in `MemoryAdapter` because nobody had the need until now. Would you love to make this possible? Thank you.

**Comment by cgarvis** [comment]
I use the memory adapter locally for TDD and the use the SQL adapter for CI and production. Having a memory adapter is a big selling point for me.




I'll take a crack at implementing this

**Comment by guilhermeFranco** [comment]
Hey guys ! I'm interested in this feature too. Are you guys working on this one ? May I jump into it ? :dart: @cgarvis @jodosha

**Comment by joneslee85** [comment]
@guilhermeFranco please do
