### ISSUE TITLE
` lotus db migrate` should not raise errors if migrations folder is empty

### ISSUE THREAD

**Issue by joneslee85** [lotus/model#208]
*Given* that my `db/migrations` is empty
*When* I run `bundle exec lotus db migrate`
*Then* I should not see following errors:

```
success_o_tron:lotus-blog tle$ bundle exec lotus db prepare
/Users/tle/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/lotus-model-0.4.1/lib/lotus/model/migrator.rb:161:in `rescue in migrate': No target version available, probably because no migration files found or filenames don't follow the migration filename convention (Lotus::Model::MigrationError)
        from /Users/tle/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/lotus-model-0.4.1/lib/lotus/model/migrator.rb:157:in `migrate'
        from /Users/tle/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/lotus-model-0.4.1/lib/lotus/model/migrator.rb:248:in `prepare'
        from /Users/tle/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/lotusrb-0.4.1/lib/lotus/commands/db/prepare.rb:9:in `start'
        from /Users/tle/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/lotusrb-0.4.1/lib/lotus/commands/db.rb:90:in `prepare'
        from /Users/tle/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /Users/tle/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/tle/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /Users/tle/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
        from /Users/tle/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
        from /Users/tle/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /Users/tle/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/tle/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /Users/tle/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /Users/tle/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/lotusrb-0.4.1/bin/lotus:4:in `<top (required)>'
        from /Users/tle/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bin/lotus:23:in `load'
        from /Users/tle/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bin/lotus:23:in `<main>'
```

**Comment by g3d** [comment]
@joneslee85 will look into that

**Comment by g3d** [comment]
This error was related to https://github.com/jeremyevans/sequel/blob/4.24.0/lib/sequel/extensions/migration.rb#L511. 

Steps to reproduce:
1) you have non-empty folder without migration (.gitkeep, etc)
2) you run `bundle exec rake db migrate`
3) you got that error

Created PR for that
