### ISSUE TITLE
`lotus db drop` fails saying "Cannot find database" (postgres)

### ISSUE THREAD

**Issue by ericboehs** [lotus/model#209]
When trying to drop a postgres database, a `Cannot find database` error is thrown.

```
lotus new itshot --database=postgres
cd itshot
lotus db create
lotus db drop
```
Last commands fails with:

```
lotus-model-0.4.1/lib/lotus/model/migrator/postgres_adapter.rb:42:in `rescue in drop':
  Cannot find database: itshot_development (Lotus::Model::MigrationError)
lotus-model-0.4.1/lib/lotus/model/migrator/postgres_adapter.rb:34:in `drop'
lotus-model-0.4.1/lib/lotus/model/migrator.rb:111:in `drop'
lotusrb-0.4.1/lib/lotus/commands/db/drop.rb:9:in `start'
lotusrb-0.4.1/lib/lotus/commands/db.rb:46:in `drop'
thor-0.19.1/lib/thor/command.rb:27:in `run'
thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
thor-0.19.1/lib/thor.rb:359:in `dispatch'
thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
thor-0.19.1/lib/thor/command.rb:27:in `run'
thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
thor-0.19.1/lib/thor.rb:359:in `dispatch'
thor-0.19.1/lib/thor/base.rb:440:in `start'
lotusrb-0.4.1/bin/lotus:4:in `<top (required)>'
```

I have not tested this on MySQL. Perhaps the same issue is there as well.

**Comment by ziggurat** [comment]
I think this PR will fix this issue https://github.com/lotus/model/pull/213

**Comment by joneslee85** [comment]
@ericboehs to me the problem seems to lie at the create part. There is a now a fix for creation upstream, you can try it out with lotus-model HEAD. 

@ziggurat I tested the drop task for postgresql and it works perfectly.
