### ISSUE TITLE
Too many open files error when running tests

### ISSUE THREAD

**Issue by stepantubanov** [lotus/model#242]
Hey,

I am getting some errors when running tests, could you give me a hand in figuring out what's wrong?

There are 15 errors in total, but they're all of 2 types:
1) SQLite not being able to open database file
2) Too many files open (file adapter tests)

Examples below:
```
Lotus::Model::Adapters::SqlAdapter::#query::asc::with an empty collection#test_0001_returns an empty result set:
Sequel::DatabaseConnectionError: SQLite3::CantOpenException: unable to open database file
    /Users/stepan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.26.0/lib/sequel/adapters/sqlite.rb:107:in `initialize'
    /Users/stepan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.26.0/lib/sequel/adapters/sqlite.rb:107:in `new'
    /Users/stepan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.26.0/lib/sequel/adapters/sqlite.rb:107:in `connect'
    /Users/stepan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.26.0/lib/sequel/connection_pool.rb:101:in `make_new'
    /Users/stepan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.26.0/lib/sequel/connection_pool/threaded.rb:222:in `make_new'
    /Users/stepan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.26.0/lib/sequel/connection_pool/threaded.rb:195:in `available'
    /Users/stepan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.26.0/lib/sequel/connection_pool/threaded.rb:131:in `_acquire'
    /Users/stepan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.26.0/lib/sequel/connection_pool/threaded.rb:145:in `block in acquire'
    /Users/stepan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.26.0/lib/sequel/connection_pool/threaded.rb:263:in `block in sync'
    /Users/stepan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.26.0/lib/sequel/connection_pool/threaded.rb:263:in `synchronize'
    /Users/stepan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.26.0/lib/sequel/connection_pool/threaded.rb:263:in `sync'
    /Users/stepan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.26.0/lib/sequel/connection_pool/threaded.rb:144:in `acquire'
    /Users/stepan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.26.0/lib/sequel/connection_pool/threaded.rb:102:in `hold'
    /Users/stepan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.26.0/lib/sequel/database/connecting.rb:249:in `synchronize'
    /Users/stepan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.26.0/lib/sequel/adapters/sqlite.rb:178:in `_execute'
    /Users/stepan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.26.0/lib/sequel/adapters/sqlite.rb:133:in `execute_dui'
    /Users/stepan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.26.0/lib/sequel/dataset/actions.rb:932:in `execute_dui'
    /Users/stepan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.26.0/lib/sequel/dataset/actions.rb:122:in `delete'
    /Users/stepan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.26.0/lib/sequel/adapters/shared/sqlite.rb:570:in `delete'
    /Users/stepan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.26.0/lib/sequel/adapters/shared/sqlite.rb:570:in `delete'
    /Users/stepan/oss/model/lib/lotus/model/adapters/sql/command.rb:58:in `delete'
    /Users/stepan/oss/model/lib/lotus/model/adapters/sql_adapter.rb:102:in `clear'
    /Users/stepan/oss/model/test/model/adapters/sql_adapter_test.rb:98:in `block (2 levels) in <top (required)>'


  2) Error:
Lotus::Model::Adapters::FileSystemAdapter::#query::count::with an empty collection#test_0001_returns 0:
Errno::EMFILE: Too many open files - getcwd
    /Users/stepan/.rbenv/versions/2.2.2/lib/ruby/2.2.0/pathname.rb:563:in `require'
    /Users/stepan/.rbenv/versions/2.2.2/lib/ruby/2.2.0/pathname.rb:563:in `mkpath'
    /Users/stepan/oss/model/lib/lotus/model/adapters/file_system_adapter.rb:244:in `prepare'
    /Users/stepan/oss/model/lib/lotus/model/adapters/file_system_adapter.rb:71:in `initialize'
    /Users/stepan/oss/model/test/model/adapters/file_system_adapter_test.rb:49:in `new'
    /Users/stepan/oss/model/test/model/adapters/file_system_adapter_test.rb:49:in `block (2 levels) in <top (required)>'
```

I'm using ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14], SQLite version 3.8.11.1

**Comment by AlfonsoUceda** [comment]
@stepantubanov sorry for the late response, what OS do you have? mac os x?

**Comment by hlegius** [comment]
Just for the record, I am getting these errors now and then too. Travis CI is suffering with this as well. My PR has some random failures related to it.

Is there someone working on it?

**Comment by jodosha** [comment]
@hlegius Nope, sorry. :(

**Comment by stepantubanov** [comment]
@AlfonsoUceda yep, mac os x 10.11.

**Comment by hlegius** [comment]
@jodosha can I take a look on it, then?
Is everybody getting these errors in yours local's env?

**Comment by AlfonsoUceda** [comment]
@hlegius that is a problem related to mac os x, search in google about that error and how to fix it

**Comment by hlegius** [comment]
@AlfonsoUceda hmm.. but it happens inside Travis [Jobs](https://travis-ci.org/lotus/model/jobs/83631364#L353) sometimes - maybe is not 100% related to this one reported here, but is also this sqlite random error. If you run it on localhost (Linux) you can reproduce, but when running only the 'broken' test, it passes.

Here is [another example](https://travis-ci.org/lotus/model/jobs/83477891#L164) and [another from PR 239](https://travis-ci.org/lotus/model/jobs/80532485#L164).

Do you think those are related to this one?

**Comment by jodosha** [comment]
> can I take a look on it, then?

@hlegius Absolutely, thank you :green_heart:
