### ISSUE TITLE
Misleading error message for non configured mapper

### ISSUE THREAD

**Issue by jodosha** [lotus/model#249]
When we create a fresh new app and one entity/repository, but we **don't** configure the mapper, we get this misleading error message:

Expected:

```
Lotus::Model::Adapters::NoMappingError: Please configure data mapper.
```

Current:

```
Run options: --seed 6465

# Running:

E

Finished in 0.001145s, 873.2892 runs/s, 0.0000 assertions/s.

  1) Error:
BookRepository#test_0001_clears the database:
Lotus::Model::Adapters::NoAdapterError: Cannot invoke `clear' without selecting an adapter. Please check your framework configuration.
    /Users/luca/.gem/ruby/2.2.3/gems/lotus-model-0.5.0/lib/lotus/model/adapters/null_adapter.rb:15:in `method_missing'
    /Users/luca/.gem/ruby/2.2.3/gems/lotus-model-0.5.0/lib/lotus/repository.rb:521:in `clear'
    /Users/luca/Desktop/bookshelf/spec/bookshelf/repositories/book_repository_spec.rb:5:in `block (2 levels) in <top (required)>'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -I"lib:spec" -I"/Users/luca/.rubies/ruby-2.2.3/lib/ruby/2.2.0" "/Users/luca/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/rake_test_loader.rb" "spec/**/*_spec.rb" ]

Tasks: TOP => default => test
(See full trace by running task with --trace)
```

Steps to reproduce:

```ruby
% lotus new bookshelf --database=postgres && cd bookshelf && bundle
% bundle exec lotus generate model book
% LOTUS_ENV=test bundle exec lotus db prepare
% vim spec/bookshelf/repositories/book_repository_spec.rb
% bundle exec rake
```

```ruby
# spec/bookshelf/repositories/book_repository_spec.rb
require 'spec_helper'

describe BookRepository do
  before do
    BookRepository.clear
  end

  it 'clears the database' do
    BookRepository.all.must_equal []
  end
end
```

/cc @lotus/core-team

**Comment by huynhquancam** [comment]
@jodosha @joneslee85  Do you think we can check if collections have been configured at this mapper building step? 
https://github.com/lotus/model/blob/master/lib/lotus/model/configuration.rb#L250

**Comment by jodosha** [comment]
@huynhquancam :-1: This happens when there is no corresponding collection for a given repository.

For instance, if my mapping has:

```ruby
  mapping do
    collection :authors do
      entity     Author
      repository AuthorRepository

      attribute :id,   Integer
      attribute :name, String
    end

    # missing :books collection
  end
```

If you run the tests again, you'll get the same error.

I think `NullAdapter` should accept a name for the initializer and provide a batter error message.

```ruby
# lib/lotus/repository.rb
        self.adapter = Lotus::Model::Adapters::NullAdapter.new(name)
```

```ruby
# lib/lotus/model/adapters/null_adapter.rb
module Lotus
  module Model
    module Adapters
      # @since 0.2.0
      class NoAdapterError < ::StandardError
        def initialize(repository, method_name)
          super("Cannot invoke `#{ method_name }' without mapping #{ repository }. Please check your framework configuration.")
        end
      end

      # @since 0.2.0
      # @api private
      class NullAdapter
        def initialize(name)
          @name = name
        end

        def method_missing(m, *args)
          raise NoAdapterError.new(@name, m)
        end
      end
    end
  end
end
```

**Comment by huynhquancam** [comment]
@jodosha thanks, :+1:  I think your approach works but SRP wise, seriously do you think the adapter needs to care about which repository it's being attached to?

How about `NullAdapter` to accept a `NullMapper` by default?

```ruby
# lib/lotus/model/repository.rb
module Repository
    # Inject the public API into the hosting class.
    #
    # @since 0.1.0
    #
    # @example
    #   require 'lotus/model'
    #
    #   class UserRepository
    #     include Lotus::Repository
    #   end
    def self.included(base)
      base.class_eval do
        extend ClassMethods
        include Lotus::Utils::ClassAttribute

        class_attribute :collection
        self.adapter = Lotus::Model::Adapters::NullAdapter.new(Lotus::Model::NullMapper.new(repository_name))
      end
    end
end
```

```ruby
# lib/lotus/model/adapters/null_adapter.rb
module Lotus
  module Model
    module Adapters
      # @since 0.2.0
      class NoAdapterError < ::StandardError
        def initialize(mapping_name, method_name)
          super("Cannot invoke `#{ method_name }' without mapping #{ mapping_name }. Please check your framework configuration.")
        end
      end

      # @since 0.2.0
      # @api private
      class NullAdapter
        def initialize(mapping)
          @mapping = mapping
        end

        def method_missing(m, *args)
          raise NoAdapterError.new(@mapping.repository_name, m)
        end
      end
    end
  end
end
```

**Comment by jodosha** [comment]
@huynhquancam 
> seriously do you think the adapter needs to care about which repository it's being attached to?

I think this is true for `NullMapper` too. Your approach mimics the relation between adapter and mapper, but it looks like an unnecessary indirection.

**Comment by trantuanckc** [comment]
Note again for any body (and for me :D ) still have this problem. (work for me) in `lib/<app name>.rb`
If you load specify mapping file `mapping "#{__dir__}/config/mapping"`
You should comment the mapping block below

```
# mapping do
    # collection :users do
    #   entity     User
    #   repository UserRepository
    #
    #   attribute :id,   Integer
    #   attribute :name, String
    # end
  # end
```

Thanks to @jodosha to support me! :100:

**Comment by huynhquancam** [comment]
:+1:

**Comment by jodosha** [comment]
As future reference: last evaluation of `mapping` wins. If you have a mapping loaded from an external file (eg. `lib/bookshelf/config/mapping.rb`) **AND** an empty `mapping` block, the last one will take precedence.

Here a code example of an **INVALID** configuration:

```ruby
# lib/bookshelf.rb
# ...
Lotus::Model.configure do
  mapping "#{__dir__}/config/mapping"

  mapping do
    # empty mapping will take precedence and clears the previous definitions of `mapping`
  end
end.load!
```
