### ISSUE TITLE
Improve error message for `lotus db drop`

### ISSUE THREAD

**Issue by jodosha** [lotus/model#250]
Steps to reproduce.

```shell
% lotus new bookshelf --database=postgres && cd bookshelf && bundle
% bundle exec lotus db prepare
```

Open another shell and left open the PG client

```shell
% psql bookshelf_development
```

Get back to the initial shell:

```shell
% bundle exec lotus db drop
/Users/luca/.gem/ruby/2.2.3/gems/lotus-model-0.5.0/lib/lotus/model/migrator/postgres_adapter.rb:51:in `block in drop': Lotus::Model::MigrationError (Lotus::Model::MigrationError)
        from /Users/luca/.rubies/ruby-2.2.3/lib/ruby/2.2.0/open3.rb:199:in `popen_run'
        from /Users/luca/.rubies/ruby-2.2.3/lib/ruby/2.2.0/open3.rb:93:in `popen3'
        from /Users/luca/.gem/ruby/2.2.3/gems/lotus-model-0.5.0/lib/lotus/model/migrator/postgres_adapter.rb:39:in `drop'
        from /Users/luca/.gem/ruby/2.2.3/gems/lotus-model-0.5.0/lib/lotus/model/migrator.rb:112:in `drop'
        from /Users/luca/.gem/ruby/2.2.3/gems/lotusrb-0.5.0/lib/lotus/commands/db/drop.rb:9:in `start'
        from /Users/luca/.gem/ruby/2.2.3/gems/lotusrb-0.5.0/lib/lotus/commands/db.rb:46:in `drop'
        from /Users/luca/.gem/ruby/2.2.3/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /Users/luca/.gem/ruby/2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/luca/.gem/ruby/2.2.3/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /Users/luca/.gem/ruby/2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
        from /Users/luca/.gem/ruby/2.2.3/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
        from /Users/luca/.gem/ruby/2.2.3/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /Users/luca/.gem/ruby/2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/luca/.gem/ruby/2.2.3/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /Users/luca/.gem/ruby/2.2.3/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /Users/luca/.gem/ruby/2.2.3/gems/lotusrb-0.5.0/bin/lotus:4:in `<top (required)>'
        from /Users/luca/.gem/ruby/2.2.3/bin/lotus:23:in `load'
        from /Users/luca/.gem/ruby/2.2.3/bin/lotus:23:in `<main>'
```

The reason is that `dropdb` fails, because we forgot the other shell open with a connected client. The problem is that we don't see any help in the error message.

For instance if I try with `dropdb` I see the problem and how to fix it.

```shell
% dropdb bookshelf_development
dropdb: database removal failed: ERROR:  database "bookshelf_development" is being accessed by other users
DETAIL:  There is 1 other session using the database.
```

**Comment by t4deu** [comment]
Hi @jodosha ans @joneslee85, I can take a look on this and on the #251 if it is not a problem

**Comment by joneslee85** [comment]
@t4deu please go ahead
